---@class cB3DDDC2A : cB3DDDC2A_instance
---@field f4DF89DC5 fun(x:userdata,y:userdata):boolean @ IsEqual
---@field fF749F3D1 fun(x:userdata,y:userdata):boolean @ NotEqual
---@field f5B6373D5 fun():cB3DDDC2A
cB3DDDC2A = {}  -- dummy

---@class cB3DDDC2A_instance : userdata
---@field f39DD249C fun(self:self,x:c535A0125):userdata
---@field fC723824A fun(self:self,x:number,y:string,z:string):void
---@field f631566D3 fun(self:self,x:number):void
---@field f14125645 fun(self:self,x:number,y:userdata,z:number,a:number):void
---@field f45F33B6E fun(self:self,x:number,y:userdata):void
---@field fD83C075C fun(self:self,x:number,y:userdata):void
---@field fEB298455 fun(self:self,x:number,y:number):void
---@field f9C2EB4C3 fun(self:self,x:number,y:number,z:number):void
---@field f3AE0BF47 fun(self:self,x:number,y:number,z:boolean):void
---@field fD499C005 fun(self:self,x:number,y:userdata):void
---@field f8FC99F59 fun(self:self,x:number,y:number,z:userdata):void
---@field fCAF3F960 fun(self:self,x:number,y:userdata):void
---@field fA0CC3CEA fun(self:self,x:number,y:number,z:number):void
---@field f415EF4C6 fun(self:self,x:number,y:number):void
---@field fABEB9F55 fun(self:self,x:number,y:number,z:number,a:number,b:number):void
---@field f4F93905F fun(self:self,x:number,y:number):void
---@field f3894A0C9 fun(self:self,x:number,y:userdata):void
---@field f846B6612 fun(self:self,x:number,y:number):void
---@field fF36C5684 fun(self:self,x:number,y:userdata):void
---@field f25A88347 fun(self:self,x:number,y:number,z:number):void
---@field f644EBF7C fun(self:self,x:number,y:number):void
---@field f13AD502E fun(self:self,x:number,y:number):void
---@field fCB6BF1D5 fun(self:self,x:number,y:number):void
---@field fB79E5BAA fun(self:self,x:number,y:userdata,z:number):void
---@field f0E8413AF fun(self:self,x:number,y:string):void
---@field f853BCAC0 fun(self:self):void
