---@class cECB91E31 : cECB91E31_instance
---@field fB6A00A1B fun(x:cECB91E31_instance,y:cECB91E31_instance):boolean @ IsEqual
---@field f04ACC3F2 fun(x:cECB91E31_instance,y:cECB91E31_instance):boolean @NotEqual
---@field fB41FD22F fun(x:c016374C1):cECB91E31
cECB91E31 = {}  -- dummy

---@class cECB91E31_instance : userdata
---@field f2C7B9325 fun(self:self):boolean
---@field fE08FDDDD fun(self:self,x:boolean):void
---@field f1447AC81 fun(self:self):boolean
---@field f2CB8758F fun(self:self):boolean
---@field f6754453E fun(self:self,x:boolean):void
---@field f802FE4CC fun(self:self,x:boolean):void
---@field fBE611951 fun(self:self):number
---@field fA661CF08 fun(self:self,x:string):number
---@field f799716B9 fun(self:self,x:number,y:string):boolean
---@field f1DCEA80B fun(self:self,x:number,y:boolean,z:string):void
---@field f7AE7CD43 fun(self:self,x:number,y:string):number,number,number,number
---@field f5DA11010 fun(self:self,x:number,y:string):number,number,number,number
---@field fEFEBD7E3 fun(self:self,x:string,y:string):number
---@field f63CCD91E fun(self:self,x:number,y:string):c6C285ADF
---@field f096E09B7 fun(self:self,x:number,y:string):c6C285ADF
---@field f42B1A1FF fun(self:self,x:number,y:cA5D89E23,z:string):void
---@field f07AAF256 fun(self:self,x:number,y:string):void
---@field fE8E82325 fun(self:self,x:string):void
---@field fFA5C9904 fun(self:self,x:number,y:string):cCE8E2D0A
---@field f4D93367B fun(self:self,x:number,y:string):cCE8E2D0A
---@field f716E208D fun(self:self):number
---@field fCF5F8B12 fun(self:self):number
---@field fD1703C5B fun(self:self,x:number):void
---@field fDBC4B1DD fun(self:self):number,number,number,number
---@field f1202A24A fun(self:self,x:string):number,number,number,number
---@field fEBD02BB0 fun(self:self):number,number,number,number
---@field fEEF8EB33 fun(self:self,x:number):string
---@field fD74EB814 fun(self:self):number
---@field f949BDB20 fun(self:self,x:boolean,y:string):void
---@field f178CCE0E fun(self:self,x:string):boolean
---@field f947FBB06 fun(self:self,x:number,y:boolean,z:string):void
---@field fFBFCB000 fun(self:self,x:string,y:string,z:string,a:cE2FA79C6):void
---@field f539B2749 fun(self:self,x:string,y:string,z:cE2FA79C6):void
---@field f376CD857 fun(self:self,x:boolean):void
---@field f5BCBC57C fun(self:self):number
---@field f007761BF fun(self:self,x:string,y:number,z:number,a:number,b:string,c:string):void
---@field f77705129 fun(self:self,x:string,y:number,z:number,a:number,b:number,c:string,d:string):void
---@field fEE790093 fun(self:self,x:string,y:cCE8E2D0A,z:string,a:string):void
---@field fA96DA14C fun(self:self,x:string,y:number,z:string,a:string):void
---@field fB619BC7D fun(self:self,x:string,y:number,z:string,a:string):void
---@field fABD1B248 fun(self:self,x:string,y:number,z:string):void
---@field f557EB064 fun(self:self,x:string,y:number,z:number,a:number,b:number,c:string):void
---@field fAD2280D7 fun(self:self,x:string,y:number,z:string):void
